server:
  port: 10086
spring:
  application:
    name: ly-registry #serviceID
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.199:10086/eureka # 配置 Eureka-Server 地址
    fetch-registry: false  # 该实例是否向 Eureka 服务器获取所有的注册信息表
    register-with-eureka: false # 该实例是否向 Eureka  Server注册自己
